import fs from 'node:fs';
import {median} from './winner-analysis.mjs';
const result=JSON.parse(fs.readFileSync('docs/benchmarks/2026-10-08-winner-summary.json'));
if(result.attempts.some(x=>!x.summary.complete))throw new Error('Report incomplete attempts explicitly');
const name=id=>id==='lexical'?'BM25':id.includes('e5')?'E5-small multilingual':'MiniLM multilingual';
const number=x=>Number.isFinite(x)?x.toFixed(2):'n/a';
const lines=['## Results','',
  'All three scheduled attempts completed without failed or repeated scored inference: 188 query cases, 1,880 retained ranking rows across the fixed strategies. The real task pool has sixteen sources; the document pool has eighteen. Thirty-two matching task requests are English/Hebrew variants of sixteen task families in one project, not thirty-two independent projects.','',
  '### Real task source recovery','',
  '| Retriever | Strategy | R@1 /32 | R@5 /32 | R@10 /32 | MRR@10 |',
  '| --- | --- | ---: | ---: | ---: | ---: |'];
for(const a of result.attempts)for(const s of a.summary.scores.filter(x=>x.suite==='real'&&x.language==='all'))lines.push(`| ${name(a.summary.model)} | ${s.strategy} | ${s.raw.r1}/32 | ${s.raw.r5}/32 | ${s.raw.r10}/32 | ${number(s.raw.mrr10)} |`);
lines.push('', 'E5 whole-intent retrieval had the highest observed first-source recovery in this small real-project sample. Splitting every short intent into small sections reduced first-place precision; sections are not automatically the better representation. The hybrid reached 32/32 in the top ten for both models but lowered first-place recovery. This supports further testing of separate compact-intent and long-document channels, not a universal model winner.','',
  '### Requirements placed after a long appendix','',
  '| Retriever | Strategy | R@1 /32 | R@5 /32 | R@10 /32 | MRR@10 |', '| --- | --- | ---: | ---: | ---: | ---: |');
for(const a of result.attempts)for(const s of a.summary.scores.filter(x=>x.suite==='late'&&x.language==='all'))lines.push(`| ${name(a.summary.model)} | ${s.strategy} | ${s.raw.r1}/32 | ${s.raw.r5}/32 | ${s.raw.r10}/32 | ${number(s.raw.mrr10)} |`);
lines.push('', 'All sixteen whole-intent stress inputs exceeded both encoder windows. Their early padding was identical, so whole-source vectors lost the distinguishing requirements: 2/32 first-place and 20/32 top-ten results are tied-rank recovery, not semantic success. Section retrieval recovered the actual late requirements; E5 rose to 18/32 first and 31/32 top ten, MiniLM to 15/32 and 31/32. BM25 searched the full text and did not suffer encoder truncation. This is controlled placement stress, not naturally collected giant-project history. Offsets in this suite resolve to the frozen synthetic snapshots, not live canonical ledger files.','',
  '### Linked Markdown sources and headings','',
  '| Retriever | Strategy | Source R@1 /12 | Source R@5 /12 | Source R@10 /12 | Correct source and heading at1 /12 |', '| --- | --- | ---: | ---: | ---: | ---: |');
for(const a of result.attempts)for(const s of a.summary.scores.filter(x=>x.suite==='documents'&&x.language==='all'))lines.push(`| ${name(a.summary.model)} | ${s.strategy} | ${s.raw.r1}/12 | ${s.raw.r5}/12 | ${s.raw.r10}/12 | ${s.heading1}/12 |`);
lines.push('', 'Finding the correct document is easier than choosing the exact useful section. E5 sections recovered the designated document in the top five for 11/12 questions, but selected the designated source and heading first in only 2/12. Source recovery does not prove answer extraction, requirement coverage or trustworthy interpretation of an instruction in Markdown. Whole methods have no heading selection and their zero heading counts are structural, not a separate model failure.','',
  '### Known adversarial synthetic diagnostic','',
  '| Retriever | Strategy | Raw R@1 /48 | Raw R@10 /48 | Eligible R@1 /48 | Eligible R@10 /48 |', '| --- | --- | ---: | ---: | ---: | ---: |');
for(const a of result.attempts)for(const s of a.summary.scores.filter(x=>x.suite==='known-synthetic'&&x.language==='all'))lines.push(`| ${name(a.summary.model)} | ${s.strategy} | ${s.raw.r1}/48 | ${s.raw.r10}/48 | ${s.eligible.r1}/48 | ${s.eligible.r10}/48 |`);
lines.push('', 'These are the known previous sixteen synthetic families at 1,000 items, including extensions/opposites and old versions. They are not new independent test data. Fixed equal-rank hybrid fusion reduced raw top-ten recovery from 44/48 to 34/48 for E5 and 33/48 for MiniLM. Combining a weak lexical signal with a dense rank can hurt; no fusion parameters were changed after this outcome. Eligibility removes explicitly cancelled/superseded and wrong-version records, but does not decide semantic identity or infer scope.','',
  '### Cache, source freshness and resource checks','',
  '| Model | Fresh-process restarts | Unchanged re-encodes | Incremental checks | Corrupt-cache rebuild | Load, s | Query batch encode, s | Peak process RSS, MiB |', '| --- | ---: | ---: | ---: | --- | ---: | ---: | ---: |');
for(const a of result.attempts.filter(x=>x.summary.model!=='lexical')) {const s=a.summary,r=s.resources;lines.push(`| ${name(s.model)} | ${s.cacheChecks.length} | ${s.cacheChecks.reduce((n,c)=>n+c.restart.encoded,0)} | ${s.cacheChecks.length} changes, ${s.cacheChecks.length} deletions | Passed, current sources re-encoded | ${number(r.loadSeconds)} | ${number(r.queryEncodeSeconds)} | ${number(r.peakRssBytes/2**20)} |`);}
lines.push('', 'All twenty unchanged indexes were loaded in fresh subprocesses without loading an encoder. Content changes encoded at most one new entry per check; source removal needed zero encodes and removed applicable entries. A separate corrupt-copy recovery per model rebuilt the sixteen-source initial index and matched its vectors within the fixed tolerance. Cached status is never authoritative: citations and recorded status are attached from supplied source metadata. These are research-cache contract checks, not crash-proof concurrent production index maintenance.','',
  '| Model | Source set | Representation | Unique encoded entries | Truncated encoder inputs | Initial encode/cache write, s | Cache size, KiB |', '| --- | --- | --- | ---: | ---: | ---: | ---: |');
for(const a of result.attempts.filter(x=>x.summary.model!=='lexical'))for(const index of a.summary.indexes) {
  const counts=a.summary.resources.tokenCounts['index-'+index.suite+'-'+(index.store??'None')+'-'+index.strategy];
  lines.push(`| ${name(a.summary.model)} | ${index.suite}${index.store?' '+index.store:''} | ${index.strategy} | ${index.cache.encoded} | ${counts.truncated} | ${number(index.cache.updateSeconds)} | ${number(index.cache.cacheBytes/1024)} |`);
}
lines.push('', 'All section-encoding inputs fit both models; whole-document truncations are retained in the table and raw metrics. Cache-change and corruption-rebuild encodes are infrastructure checks, excluded from quality scoring. Initial update time includes encoding, compression and writing the derived cache. Per-row search time includes shared lexical/dense ranking and candidate view construction; it is not isolated neural inference or an end-to-end agent latency comparison. The Windows desktop and recorder stayed active; this is not exclusive hardware.','',
  '### Safety and unresolved questions','',
  'Every returned result includes its frozen content hash, source path, exact offsets, excerpt and recorded status, with identityEstablished=false, verification=not_checked and decision=candidate_only. No-match queries still returned candidates: all eight unrelated real requests and all forty-eight known synthetic no-match requests. This design prevents the interface from claiming a verified answer; it does not detect no-match automatically. No real task was merged, closed or verified by model inference.','',
  'The next candidate architecture is E5 for compact intent, a separate section index for long linked Markdown, and an agent-reviewed relation/source check. That is an inference from these results, not a deployed feature. Heading localization needs improvement, fusion requires signal-aware evaluation, and independent multi-project labels plus downstream agent code quality remain open. Neither this study nor the previous one trained a custom 10M/100M model.','',
  '[All results, language slices, cache checks and resource counts](2026-10-08-winner-summary.json). Compressed raw candidate lists and SHA-256 hashes are listed in the summary. Validation: node scripts/winner-check.mjs; deterministic local cache contracts: python scripts/winner-index-test.py. Preregistration and frozen runner source: [6e0ceae](https://github.com/vxu-labs/dip/commit/6e0ceae6a3d4339ee549f2160c5857fbb6a211d7). The source snapshot came from published commit 88e2bf4. Validation reads frozen sources and never executes their Markdown instructions.','');
const file='docs/benchmarks/winner-retrieval.md';const intro=fs.readFileSync(file,'utf8').split('\n## Results')[0];fs.writeFileSync(file,intro.trimEnd()+'\n\n'+lines.join('\n'));
console.log(file);
